version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh

  web:
    build: .
    command: >
      bash -c "sed -i 's/\r$//' /app/start_playwright_server.sh && 
             chmod +x /app/start_playwright_server.sh &&
             python -c 'from app import create_app; app = create_app(); app.app_context().push(); from app import db; db.create_all()' && 
             waitress-serve --port=5000 --call app:create_app"
    volumes:
      - .:/app
      - ./data:/app/data
      - playwright_browsers:/app/ms-playwright
    ports:
      - "5000:5000"
    devices:
      - /dev/random:/dev/random
      - /dev/urandom:/dev/urandom
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - REDIS_URL=redis://redis:6379
      - DOCKER_ENV=true
      - TZ=Asia/Ho_Chi_Minh
      - PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright
    depends_on:
      - redis
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  rq-worker:
    build: .
    command: >
      bash -c "set -e &&
             sed -i 's/\r$//' /app/start_playwright_server.sh && 
             chmod +x /app/start_playwright_server.sh &&
             echo 'Installing Playwright browsers' &&
             python -m playwright install chromium &&
             echo 'Starting worker and Playwright server' &&
             bash /app/start_playwright_server.sh & 
             sleep 14 &&
             python -m rq.cli worker default --url redis://redis:6379 --worker-class app.WindowsSimpleWorker --with-scheduler --verbose"
    volumes:
      - .:/app
      - ./data:/app/data
      - playwright_browsers:/app/ms-playwright
    devices:
      - /dev/random:/dev/random
      - /dev/urandom:/dev/urandom
    environment:
      - REDIS_URL=redis://redis:6379
      - DOCKER_ENV=true
      - PYTHONUNBUFFERED=1
      - PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - redis
      - web
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  redis_data:
  playwright_browsers: 